<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Gabriel Orso">

<title>Mínimos Quadrados Ordinários – Gabriel Orso</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-eddc731e2ca89861e58fd1fe1b5d2063.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-THCB1Q3SM7"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-THCB1Q3SM7', { 'anonymize_ip': true});
</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Gabriel Orso</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ufsm" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">UFSM</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ufsm">    
        <li>
    <a class="dropdown-item" href="./concurso-ufsm.html">
 <span class="dropdown-text">Concurso</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./dendrometria.html">
 <span class="dropdown-text">Dendrometria - CFL1040</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./manejoflorestal.html">
 <span class="dropdown-text">Manejo Florestal - CFL1056</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="./MQO.html" aria-current="page"> 
<span class="menu-text">MQO</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">R</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-r">    
        <li>
    <a class="dropdown-item" href="./ggplot.html">
 <span class="dropdown-text">ggplot2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./dplyr.html">
 <span class="dropdown-text">dplyr</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./Simulacao.html"> 
<span class="menu-text">Simulação</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./d2h.html"> 
<span class="menu-text">Aplicativo d2h</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mínimos Quadrados Ordinários</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Gabriel Orso </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gganimate)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Utilizaremos o banco de dados <strong>trees</strong>. Esse banco de dados contém informações sobre o diâmetro em polegadas, altura em pés e volume em pés³ de 31 árvores <em>black cherry</em>.</p>
<p>Além disso, os gráficos serão gerados utilizando o pacote <code>ggplot2</code>, com comentários pertinentes sobre as funções utilizadas. Os comandos do pacote <code>ggplot2</code> são inseridos em camadas, normalmente iniciando por uma função que indica o banco de dados utilizado e, posteriormente, pelas demais funções. As variáveis utilizadas para criar os gráficos devem estar “mapeadas”, e a maneira de fazer isso é inserindo-as dentro do argumento <code>aes()</code>. No exemplo abaixo, o primeiro nível de comando especifica o banco de dados utilizado. O segundo indica o tipo de gráfico a ser criado e mapeia as variáveis de interesse. O terceiro comando introduz os títulos dos eixos, do gráfico etc. E o quarto comando aplica um tema pronto ao gráfico. Para mais informações sobre o pacote <code>ggplot2</code>, acesse este <a href="ggplot.html">breve tutorial</a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"trees"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Transforma as variáveis para unidades comumente utilizadas</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>d  <span class="ot">&lt;-</span> trees<span class="sc">$</span>Girth <span class="sc">*</span> <span class="fl">2.54</span>       <span class="co"># polegadas para centímetros</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>ht <span class="ot">&lt;-</span> trees<span class="sc">$</span>Height <span class="sc">*</span> <span class="fl">0.3048</span>    <span class="co"># pés para metros</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>v  <span class="ot">&lt;-</span> trees<span class="sc">$</span>Volume <span class="sc">/</span> <span class="fl">35.3147</span>   <span class="co"># pés cúbicos para metros cúbicos</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>d2h <span class="ot">&lt;-</span> d<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> ht</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 'd' é um vetor de diâmetros e possui 31 elementos.</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>d</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 21.082 21.844 22.352 26.670 27.178 27.432 27.940 27.940 28.194 28.448
[11] 28.702 28.956 28.956 29.718 30.480 32.766 32.766 33.782 34.798 35.052
[21] 35.560 36.068 36.830 40.640 41.402 43.942 44.450 45.466 45.720 45.720
[31] 52.324</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(d)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 31</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># O mesmo ocorre com ht, v e d2h.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Agrupa tudo em um único data frame</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(d, ht, v, d2h)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>g.base <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dados,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> d2h, <span class="at">y =</span> v)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">expression</span>(d<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> h),</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Volume (m³)"</span>,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="fu">expression</span>(<span class="st">"Volume em função de "</span> <span class="sc">*</span> d<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> h)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(g.base)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MQO_files/figure-html/Banco de dados-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A figura acima demonstra a relação entre volume e <span class="math inline">\(d^2h\)</span>. Essa relação é conhecida no meio florestal pelo modelo de Spurr,</p>
<p><span class="math display">\[
v = \beta_0 + \beta_1d^2h,
\]</span></p>
<p>e evidencia uma relação aproximadamente linear entre as duas variáveis.</p>
<p>Para encontrar os parâmetros do modelo, basta utilizar a função <code>lm()</code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>spurr <span class="ot">&lt;-</span> <span class="fu">lm</span>(v <span class="sc">~</span> d2h, <span class="at">data =</span> dados)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(spurr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = v ~ d2h, data = dados)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.130808 -0.031154 -0.004689  0.049416  0.118861 

Coefficients:
                 Estimate    Std. Error t value            Pr(&gt;|t|)    
(Intercept) -0.0084293350  0.0272848246  -0.309                0.76    
d2h          0.0000305910  0.0000008566  35.711 &lt;0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.07059 on 29 degrees of freedom
Multiple R-squared:  0.9778,    Adjusted R-squared:  0.977 
F-statistic:  1275 on 1 and 29 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(spurr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept)            d2h 
-0.00842933501  0.00003059096 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>g.base <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Modelo de Spurr ajustado"</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">intercept =</span> <span class="fu">coef</span>(spurr)[<span class="dv">1</span>],  <span class="co"># coeficiente linear (b0)</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">slope =</span> <span class="fu">coef</span>(spurr)[<span class="dv">2</span>],      <span class="co"># coeficiente angular (b1)</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"steelblue"</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MQO_files/figure-html/linear simples-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Os valores estimados de <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span> foram, respectivamente, -0.00843 e 0.00003059.</p>
<p>Agora vamos chegar aos mesmos parâmetros realizando o método dos mínimos quadrados ordinários passo a passo.</p>
<section id="mínimos-quadrados-ordinários" class="level2">
<h2 class="anchored" data-anchor-id="mínimos-quadrados-ordinários">Mínimos Quadrados Ordinários</h2>
<p>O método dos mínimos quadrados ordinários (MQO) é o principal método de estimação dos parâmetros em modelos lineares. Seu objetivo é encontrar os valores dos parâmetros que resultam na menor soma de quadrados dos resíduos.</p>
<p>É importante separar <strong>o cálculo dos estimadores de MQO</strong> dos <strong>pressupostos utilizados para estabelecer suas propriedades estatísticas e realizar inferência</strong>. A minimização da soma de quadrados pode ser realizada mesmo sem pressupor normalidade dos erros. No modelo linear clássico, as condições usuais incluem:</p>
<ul>
<li><strong>1. Média condicional do erro igual a zero:</strong> <span class="math inline">\(E(\epsilon_i \mid X) = 0\)</span>;</li>
<li><strong>2. Homocedasticidade:</strong> <span class="math inline">\(\operatorname{Var}(\epsilon_i \mid X) = \sigma^2\)</span>;</li>
<li><strong>3. Ausência de correlação entre os erros:</strong> <span class="math inline">\(\operatorname{Cov}(\epsilon_i,\epsilon_j \mid X)=0\)</span>, para <span class="math inline">\(i \neq j\)</span>.</li>
</ul>
<p>Quando se deseja realizar inferência exata em amostras finitas por meio das distribuições <span class="math inline">\(t\)</span> e <span class="math inline">\(F\)</span>, é comum acrescentar a hipótese de normalidade:</p>
<p><span class="math display">\[
\boldsymbol{\epsilon}\mid X \sim N(\mathbf{0},\sigma^2I).
\]</span></p>
<blockquote class="blockquote">
<p>A normalidade dos erros não é necessária para calcular os estimadores de MQO nem para o resultado de Gauss–Markov. Ela é uma hipótese adicional para a inferência exata no modelo linear normal.</p>
</blockquote>
<p>A formulação tradicional do modelo linear simples é</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1x_i + \epsilon_i.
\]</span></p>
<p>Onde <span class="math inline">\(\beta_0\)</span> é o intercepto ou constante; <span class="math inline">\(\beta_1\)</span> é o coeficiente angular associado à variável <span class="math inline">\(x\)</span>; e <span class="math inline">\(\epsilon_i\)</span> é o erro aleatório da <span class="math inline">\(i\)</span>-ésima observação, representando a diferença entre o valor observado e o valor esperado pelo modelo. Outra notação encontrada na literatura é <span class="math inline">\(y = \alpha + \beta x + \epsilon\)</span>.</p>
<p>O valor esperado de <span class="math inline">\(y_i\)</span>, condicionado a <span class="math inline">\(x_i\)</span>, é</p>
<p><span class="math display">\[
E(Y_i\mid x_i) = \beta_0 + \beta_1x_i.
\]</span></p>
<p>Como os parâmetros verdadeiros <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span> são desconhecidos, eles são estimados a partir da amostra. Os valores ajustados ou preditos são denotados por</p>
<p><span class="math display">\[
\hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1x_i.
\]</span></p>
<p>O <strong>erro populacional</strong> é</p>
<p><span class="math display">\[
\epsilon_i = y_i - (\beta_0 + \beta_1x_i),
\]</span></p>
<p>e não é diretamente observável, pois depende dos parâmetros populacionais desconhecidos.</p>
<p>Após o ajuste do modelo, obtém-se o <strong>resíduo</strong></p>
<p><span class="math display">\[
e_i = y_i - \hat{y}_i.
\]</span></p>
<p>Portanto, erro e resíduo não são sinônimos: <span class="math inline">\(\epsilon_i\)</span> pertence ao modelo populacional, enquanto <span class="math inline">\(e_i\)</span> é calculado após a estimação do modelo.</p>
<p>Como citado anteriormente, o objetivo do MQO é encontrar os parâmetros que resultem na menor soma de quadrados dos resíduos. Se simplesmente somássemos os resíduos, valores positivos e negativos poderiam se compensar. Além disso, em uma regressão com intercepto ajustada por MQO, a soma dos resíduos é exatamente zero:</p>
<p><span class="math display">\[
\sum_{i=1}^{n}e_i = 0.
\]</span></p>
<p>Por isso, a soma simples dos resíduos não mede adequadamente a magnitude dos desvios. Ao elevar cada resíduo ao quadrado, eliminamos o sinal, penalizamos mais fortemente desvios grandes e obtemos uma função diferenciável com solução analítica conveniente.</p>
<blockquote class="blockquote">
<p>Essa ainda é uma justificativa intuitiva. Uma fundamentação probabilística adicional surge quando se assume normalidade dos erros: nesse caso, minimizar a soma de quadrados dos resíduos é equivalente a maximizar a função de verossimilhança.</p>
</blockquote>
<p>Para qualquer par de valores candidatos <span class="math inline">\(b_0\)</span> e <span class="math inline">\(b_1\)</span>, podemos escrever</p>
<p><span class="math display">\[
e_i(b_0,b_1) = y_i - b_0 - b_1x_i.
\]</span></p>
<p>Assim, a função a ser minimizada é</p>
<p><span class="math display">\[
S(b_0,b_1)
=
\sum_{i=1}^{n}e_i(b_0,b_1)^2
=
\sum_{i=1}^{n}(y_i-b_0-b_1x_i)^2.
\]</span></p>
<p>Os valores de <span class="math inline">\(b_0\)</span> e <span class="math inline">\(b_1\)</span> que minimizam essa função serão chamados de <span class="math inline">\(\hat{\beta}_0\)</span> e <span class="math inline">\(\hat{\beta}_1\)</span>.</p>
<p>Agora, se atribuirmos valores quaisquer para <span class="math inline">\(b_0\)</span> e <span class="math inline">\(b_1\)</span> e calcularmos o somatório, obteremos um valor de <span class="math inline">\(S\)</span>. Conforme os valores dos parâmetros mudam, a Soma de Quadrados dos Resíduos também muda.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Função que calcula a soma de quadrados dos resíduos</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>S <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y, b0, b1) {</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>((y <span class="sc">-</span> b0 <span class="sc">-</span> b1 <span class="sc">*</span> x)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Para visualizar apenas o efeito de b0 sobre S,</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># mantemos b1 fixo.</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>b1.fixo <span class="ot">&lt;-</span> <span class="fu">unname</span>(<span class="fu">coef</span>(spurr)[<span class="dv">2</span>])</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>b0.centro <span class="ot">&lt;-</span> <span class="fu">unname</span>(<span class="fu">coef</span>(spurr)[<span class="dv">1</span>])</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Valores candidatos de b0 ao redor da região do mínimo</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>b_0 <span class="ot">&lt;-</span> <span class="fu">seq</span>(</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">from =</span> b0.centro <span class="sc">-</span> <span class="fl">0.10</span>,</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">to   =</span> b0.centro <span class="sc">+</span> <span class="fl">0.10</span>,</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">length.out =</span> <span class="dv">201</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcula S para cada valor de b0, mantendo b1 constante</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>S.est <span class="ot">&lt;-</span> <span class="fu">vapply</span>(</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>  b_0,</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">FUN =</span> <span class="cf">function</span>(b0) {</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">S</span>(</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> dados<span class="sc">$</span>d2h,</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> dados<span class="sc">$</span>v,</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">b0 =</span> b0,</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>      <span class="at">b1 =</span> b1.fixo</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>  },</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">FUN.VALUE =</span> <span class="fu">numeric</span>(<span class="dv">1</span>)</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">b0 =</span> b_0,</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">S =</span> S.est</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>b0.min <span class="ot">&lt;-</span> df<span class="sc">$</span>b0[<span class="fu">which.min</span>(df<span class="sc">$</span>S)]</span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>S.min <span class="ot">&lt;-</span> <span class="fu">min</span>(df<span class="sc">$</span>S)</span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a>g.S <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> b0, <span class="at">y =</span> S)) <span class="sc">+</span></span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">color =</span> S), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">expression</span>(<span class="st">"Parâmetro "</span> <span class="sc">*</span> beta[<span class="dv">0</span>]),</span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="fu">expression</span>(S <span class="sc">~</span> <span class="st">"(m"</span><span class="sc">^</span><span class="dv">3</span><span class="sc">*</span><span class="st">")"</span><span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">expression</span>(</span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Efeito de "</span> <span class="sc">*</span> beta[<span class="dv">0</span>] <span class="sc">*</span></span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a>      <span class="st">" na Soma de Quadrados dos Resíduos, com "</span> <span class="sc">*</span></span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a>      beta[<span class="dv">1</span>] <span class="sc">*</span> <span class="st">" fixo"</span></span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_gradient</span>(</span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a>    <span class="at">low =</span> <span class="st">"blue"</span>,</span>
<span id="cb12-53"><a href="#cb12-53" aria-hidden="true" tabindex="-1"></a>    <span class="at">high =</span> <span class="st">"red"</span>,</span>
<span id="cb12-54"><a href="#cb12-54" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="fu">expression</span>(S <span class="sc">~</span> <span class="st">"(m"</span><span class="sc">^</span><span class="dv">3</span><span class="sc">*</span><span class="st">")"</span><span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb12-55"><a href="#cb12-55" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-56"><a href="#cb12-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(</span>
<span id="cb12-57"><a href="#cb12-57" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> b0.min <span class="sc">-</span> <span class="fl">0.02</span>,</span>
<span id="cb12-58"><a href="#cb12-58" aria-hidden="true" tabindex="-1"></a>    <span class="at">xend =</span> b0.min <span class="sc">+</span> <span class="fl">0.02</span>,</span>
<span id="cb12-59"><a href="#cb12-59" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> S.min,</span>
<span id="cb12-60"><a href="#cb12-60" aria-hidden="true" tabindex="-1"></a>    <span class="at">yend =</span> S.min,</span>
<span id="cb12-61"><a href="#cb12-61" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">0.7</span></span>
<span id="cb12-62"><a href="#cb12-62" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-63"><a href="#cb12-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb12-64"><a href="#cb12-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-65"><a href="#cb12-65" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(g.S)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MQO_files/figure-html/Variação de S-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Na figura acima, apenas <span class="math inline">\(b_0\)</span> varia, enquanto <span class="math inline">\(b_1\)</span> permanece fixo. Dessa forma, o gráfico representa um corte unidimensional da função <span class="math inline">\(S(b_0,b_1)\)</span>. Percebe-se que existe um valor de <span class="math inline">\(b_0\)</span> para o qual <span class="math inline">\(S\)</span> é mínimo. Se repetíssemos o procedimento variando apenas <span class="math inline">\(b_1\)</span>, mantendo <span class="math inline">\(b_0\)</span> fixo, observaríamos o mesmo comportamento quadrático.</p>
<p>Na realidade, <span class="math inline">\(S\)</span> depende simultaneamente de dois parâmetros. Portanto, no caso da regressão linear simples, podemos imaginar <span class="math inline">\(S(b_0,b_1)\)</span> como uma superfície. O MQO procura o ponto mais baixo dessa superfície.</p>
<p>Uma maneira de encontrar pontos críticos de uma função diferenciável é igualar suas derivadas a zero. Entretanto, uma derivada igual a zero, isoladamente, pode indicar um ponto de mínimo, máximo ou, em problemas multidimensionais, até um ponto de sela. No caso do MQO, a função <span class="math inline">\(S\)</span> é quadrática e convexa; portanto, sob as condições usuais de posto da matriz de regressão, o ponto crítico corresponde ao mínimo global.</p>
<p>Para encontrarmos <span class="math inline">\(\hat{\beta}_0\)</span> e <span class="math inline">\(\hat{\beta}_1\)</span>, derivaremos <span class="math inline">\(S\)</span> em relação aos parâmetros. Esse procedimento é chamado de derivada parcial, denotada por <span class="math inline">\(\partial\)</span>.</p>
<p>Primeiramente, podemos expandir o quadrado:</p>
<p><span class="math display">\[
S(\beta_0,\beta_1)
=
\sum_{i=1}^{n}
(y_i-\beta_0-\beta_1x_i)^2,
\]</span></p>
<p><span class="math display">\[
S(\beta_0,\beta_1)
=
\sum_{i=1}^{n}
\left(
y_i^2
+\beta_0^2
+\beta_1^2x_i^2
-2y_i\beta_0
-2y_i\beta_1x_i
+2\beta_0\beta_1x_i
\right).
\]</span></p>
<hr>
<section id="derivada-parcial-em-relação-a-beta_0" class="level3">
<h3 class="anchored" data-anchor-id="derivada-parcial-em-relação-a-beta_0">Derivada parcial em relação a <span class="math inline">\(\beta_0\)</span></h3>
<p>As regras de derivação são as mesmas de qualquer outra diferenciação. Como a variável de interesse é <span class="math inline">\(\beta_0\)</span>, os termos que não dependem de <span class="math inline">\(\beta_0\)</span> são tratados como constantes.</p>
<p><span class="math display">\[
\frac{\partial S}{\partial \beta_0}
=
\sum_{i=1}^{n}
\left(
2\beta_0
-2y_i
+2\beta_1x_i
\right).
\]</span></p>
<p>No ponto que minimiza <span class="math inline">\(S\)</span>, <span class="math inline">\(\beta_0=\hat{\beta}_0\)</span> e <span class="math inline">\(\beta_1=\hat{\beta}_1\)</span>. Assim,</p>
<p><span class="math display">\[
\left.
\frac{\partial S}{\partial \beta_0}
\right|_{\hat{\beta}_0,\hat{\beta}_1}
=
\sum_{i=1}^{n}
\left(
2\hat{\beta}_0
-2y_i
+2\hat{\beta}_1x_i
\right)
=
0.
\]</span></p>
<p>Colocando 2 em evidência,</p>
<p><span class="math display">\[
2
\sum_{i=1}^{n}
\left(
\hat{\beta}_0-y_i+\hat{\beta}_1x_i
\right)
=
0.
\]</span></p>
<p>Dividindo por 2 e multiplicando por <span class="math inline">\(-1\)</span>,</p>
<p><span class="math display">\[
\sum_{i=1}^{n}
\left(
y_i-\hat{\beta}_0-\hat{\beta}_1x_i
\right)
=
0.
\]</span></p>
<p>Observe que o termo entre parênteses é exatamente o resíduo <span class="math inline">\(e_i\)</span>. Portanto, uma consequência do MQO em modelos com intercepto é</p>
<p><span class="math display">\[
\sum_{i=1}^{n}e_i=0.
\]</span></p>
<p>Expandindo o somatório,</p>
<p><span class="math display">\[
\sum_{i=1}^{n}y_i
-
n\hat{\beta}_0
-
\hat{\beta}_1\sum_{i=1}^{n}x_i
=
0.
\]</span></p>
<p>Dividindo tudo por <span class="math inline">\(n\)</span>,</p>
<p><span class="math display">\[
\frac{\sum_{i=1}^{n}y_i}{n}
-
\hat{\beta}_0
-
\hat{\beta}_1
\frac{\sum_{i=1}^{n}x_i}{n}
=
0.
\]</span></p>
<p>Como</p>
<p><span class="math display">\[
\bar{y}=\frac{\sum_{i=1}^{n}y_i}{n}
\qquad\text{e}\qquad
\bar{x}=\frac{\sum_{i=1}^{n}x_i}{n},
\]</span></p>
<p>temos</p>
<p><span class="math display">\[
\bar{y}
-
\hat{\beta}_0
-
\hat{\beta}_1\bar{x}
=
0,
\]</span></p>
<p>e, portanto,</p>
<p><span class="math display">\[
\boxed{
\hat{\beta}_0
=
\bar{y}
-
\hat{\beta}_1\bar{x}
}.
\]</span></p>
<hr>
</section>
<section id="derivada-parcial-em-relação-a-beta_1" class="level3">
<h3 class="anchored" data-anchor-id="derivada-parcial-em-relação-a-beta_1">Derivada parcial em relação a <span class="math inline">\(\beta_1\)</span></h3>
<p>A derivada de <span class="math inline">\(S\)</span> em relação a <span class="math inline">\(\beta_1\)</span> é</p>
<p><span class="math display">\[
\frac{\partial S}{\partial \beta_1}
=
\sum_{i=1}^{n}
\left(
2\beta_1x_i^2
-2y_ix_i
+2\beta_0x_i
\right).
\]</span></p>
<p>Colocando <span class="math inline">\(2x_i\)</span> em evidência,</p>
<p><span class="math display">\[
\frac{\partial S}{\partial \beta_1}
=
2
\sum_{i=1}^{n}
x_i
\left(
\beta_1x_i-y_i+\beta_0
\right).
\]</span></p>
<p>No ponto de mínimo,</p>
<p><span class="math display">\[
\left.
\frac{\partial S}{\partial \beta_1}
\right|_{\hat{\beta}_0,\hat{\beta}_1}
=
2
\sum_{i=1}^{n}
x_i
\left(
\hat{\beta}_1x_i-y_i+\hat{\beta}_0
\right)
=
0.
\]</span></p>
<p>Dividindo por 2,</p>
<p><span class="math display">\[
\sum_{i=1}^{n}
x_i
\left(
-y_i+\hat{\beta}_0+\hat{\beta}_1x_i
\right)
=
0.
\]</span></p>
<p>Expandindo,</p>
<p><span class="math display">\[
-\sum_{i=1}^{n}x_iy_i
+
\hat{\beta}_0\sum_{i=1}^{n}x_i
+
\hat{\beta}_1\sum_{i=1}^{n}x_i^2
=
0.
\]</span></p>
<p>Portanto,</p>
<p><span class="math display">\[
\hat{\beta}_0\sum_{i=1}^{n}x_i
+
\hat{\beta}_1\sum_{i=1}^{n}x_i^2
=
\sum_{i=1}^{n}x_iy_i.
\]</span></p>
<hr>
<p>Encontradas as duas equações, ainda precisamos resolvê-las simultaneamente. Uma solução é substituir</p>
<p><span class="math display">\[
\hat{\beta}_0
=
\bar{y}
-
\hat{\beta}_1\bar{x}
\]</span></p>
<p>na segunda equação normal:</p>
<p><span class="math display">\[
(\bar{y}-\hat{\beta}_1\bar{x})
\sum_{i=1}^{n}x_i
+
\hat{\beta}_1\sum_{i=1}^{n}x_i^2
=
\sum_{i=1}^{n}x_iy_i.
\]</span></p>
<p>Como</p>
<p><span class="math display">\[
\bar{x}
=
\frac{\sum_{i=1}^{n}x_i}{n},
\]</span></p>
<p>então</p>
<p><span class="math display">\[
\sum_{i=1}^{n}x_i=n\bar{x}.
\]</span></p>
<p>Logo,</p>
<p><span class="math display">\[
(\bar{y}-\hat{\beta}_1\bar{x})n\bar{x}
+
\hat{\beta}_1\sum_{i=1}^{n}x_i^2
=
\sum_{i=1}^{n}x_iy_i,
\]</span></p>
<p><span class="math display">\[
n\bar{x}\bar{y}
-
\hat{\beta}_1n\bar{x}^2
+
\hat{\beta}_1\sum_{i=1}^{n}x_i^2
=
\sum_{i=1}^{n}x_iy_i,
\]</span></p>
<p><span class="math display">\[
-\hat{\beta}_1n\bar{x}^2
+
\hat{\beta}_1\sum_{i=1}^{n}x_i^2
=
\sum_{i=1}^{n}x_iy_i
-
n\bar{x}\bar{y},
\]</span></p>
<p><span class="math display">\[
\hat{\beta}_1
\left(
\sum_{i=1}^{n}x_i^2-n\bar{x}^2
\right)
=
\sum_{i=1}^{n}x_iy_i
-
n\bar{x}\bar{y}.
\]</span></p>
<p>Assim,</p>
<p><span class="math display">\[
\boxed{
\hat{\beta}_1
=
\frac{
\displaystyle
\sum_{i=1}^{n}x_iy_i
-
n\bar{x}\bar{y}
}{
\displaystyle
\sum_{i=1}^{n}x_i^2
-
n\bar{x}^2
}
}
\]</span></p>
<p>ou, de forma equivalente,</p>
<p><span class="math display">\[
\boxed{
\hat{\beta}_1
=
\frac{
\displaystyle
\sum_{i=1}^{n}x_iy_i
-
\frac{
\left(\sum_{i=1}^{n}x_i\right)
\left(\sum_{i=1}^{n}y_i\right)
}{n}
}{
\displaystyle
\sum_{i=1}^{n}x_i^2
-
\frac{
\left(\sum_{i=1}^{n}x_i\right)^2
}{n}
}
}.
\]</span></p>
<p>Uma forma ainda bastante comum de escrever o mesmo estimador é</p>
<p><span class="math display">\[
\boxed{
\hat{\beta}_1
=
\frac{
\sum_{i=1}^{n}
(x_i-\bar{x})(y_i-\bar{y})
}{
\sum_{i=1}^{n}
(x_i-\bar{x})^2
}
}.
\]</span></p>
<p>Agora podemos calcular os valores de <span class="math inline">\(\hat{\beta}_0\)</span> e <span class="math inline">\(\hat{\beta}_1\)</span> diretamente.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> d2h</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> v</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(x)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimadores obtidos pelas expressões deduzidas acima</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>b1.mqo <span class="ot">&lt;-</span> (</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(x <span class="sc">*</span> y) <span class="sc">-</span> (<span class="fu">sum</span>(x) <span class="sc">*</span> <span class="fu">sum</span>(y)) <span class="sc">/</span> n</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>) <span class="sc">/</span> (</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> (<span class="fu">sum</span>(x)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>b0.mqo <span class="ot">&lt;-</span> <span class="fu">mean</span>(y) <span class="sc">-</span> b1.mqo <span class="sc">*</span> <span class="fu">mean</span>(x)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>b0.mqo</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.008429335</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>b1.mqo</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.00003059096</code></pre>
</div>
</div>
<p>O caso mostrado acima foi montado para a regressão linear simples, com os parâmetros <span class="math inline">\(\hat{\beta}_0\)</span> e <span class="math inline">\(\hat{\beta}_1\)</span>. O sistema de equações normais é</p>
<p><span class="math display">\[
\begin{cases}
n\hat{\beta}_0
+
\hat{\beta}_1\displaystyle\sum_{i=1}^{n}x_i
=
\displaystyle\sum_{i=1}^{n}y_i
\\[0.5em]
\hat{\beta}_0\displaystyle\sum_{i=1}^{n}x_i
+
\hat{\beta}_1\displaystyle\sum_{i=1}^{n}x_i^2
=
\displaystyle\sum_{i=1}^{n}x_iy_i
\end{cases}
\]</span></p>
<p>Para uma regressão linear múltipla, com mais de uma variável explicativa, o processo é semelhante, mas o número de equações normais aumenta com o número de parâmetros.</p>
<p>Quando muitas variáveis são adicionadas, é mais conveniente escrever o problema por meio de álgebra matricial.</p>
<p>Considere o modelo</p>
<p><span class="math display">\[
\mathbf{Y}
=
\mathbf{X}\boldsymbol{\beta}
+
\boldsymbol{\epsilon}.
\]</span></p>
<p>Adotaremos <span class="math inline">\(p\)</span> como o <strong>número total de parâmetros do modelo, incluindo o intercepto</strong>. Assim,</p>
<p><span class="math display">\[
\boldsymbol{\beta}
=
\begin{bmatrix}
\beta_0\\
\beta_1\\
\vdots\\
\beta_{p-1}
\end{bmatrix}_{p\times1},
\qquad
\mathbf{Y}
=
\begin{bmatrix}
y_1\\
y_2\\
\vdots\\
y_n
\end{bmatrix}_{n\times1},
\qquad
\boldsymbol{\epsilon}
=
\begin{bmatrix}
\epsilon_1\\
\epsilon_2\\
\vdots\\
\epsilon_n
\end{bmatrix}_{n\times1}.
\]</span></p>
<p>A matriz de regressão é</p>
<p><span class="math display">\[
\mathbf{X}
=
\begin{bmatrix}
1 &amp; x_{11} &amp; \cdots &amp; x_{1,p-1}\\
1 &amp; x_{21} &amp; \cdots &amp; x_{2,p-1}\\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots\\
1 &amp; x_{n1} &amp; \cdots &amp; x_{n,p-1}
\end{bmatrix}_{n\times p}.
\]</span></p>
<p>Após a estimação,</p>
<p><span class="math display">\[
\hat{\mathbf{Y}}
=
\mathbf{X}\hat{\boldsymbol{\beta}},
\]</span></p>
<p>e o vetor de resíduos é</p>
<p><span class="math display">\[
\mathbf{e}
=
\mathbf{Y}
-
\hat{\mathbf{Y}}
=
\mathbf{Y}
-
\mathbf{X}\hat{\boldsymbol{\beta}}.
\]</span></p>
<p>Assim como anteriormente, queremos minimizar a soma de quadrados dos resíduos. Para um vetor candidato de parâmetros <span class="math inline">\(\boldsymbol{\beta}\)</span>,</p>
<p><span class="math display">\[
S(\boldsymbol{\beta})
=
(\mathbf{Y}-\mathbf{X}\boldsymbol{\beta})^\top
(\mathbf{Y}-\mathbf{X}\boldsymbol{\beta}).
\]</span></p>
<p>Expandindo,</p>
<p><span class="math display">\[
S(\boldsymbol{\beta})
=
\mathbf{Y}^\top\mathbf{Y}
-
\mathbf{Y}^\top\mathbf{X}\boldsymbol{\beta}
-
\boldsymbol{\beta}^\top\mathbf{X}^\top\mathbf{Y}
+
\boldsymbol{\beta}^\top\mathbf{X}^\top\mathbf{X}\boldsymbol{\beta}.
\]</span></p>
<p>Como <span class="math inline">\(\mathbf{Y}^\top\mathbf{X}\boldsymbol{\beta}\)</span> é um escalar,</p>
<p><span class="math display">\[
\mathbf{Y}^\top\mathbf{X}\boldsymbol{\beta}
=
\boldsymbol{\beta}^\top\mathbf{X}^\top\mathbf{Y}.
\]</span></p>
<p>Portanto,</p>
<p><span class="math display">\[
S(\boldsymbol{\beta})
=
\mathbf{Y}^\top\mathbf{Y}
-
2\boldsymbol{\beta}^\top\mathbf{X}^\top\mathbf{Y}
+
\boldsymbol{\beta}^\top\mathbf{X}^\top\mathbf{X}\boldsymbol{\beta}.
\]</span></p>
<p>O gradiente em relação a <span class="math inline">\(\boldsymbol{\beta}\)</span> é</p>
<p><span class="math display">\[
\nabla_{\boldsymbol{\beta}}S
=
-2\mathbf{X}^\top\mathbf{Y}
+
2\mathbf{X}^\top\mathbf{X}\boldsymbol{\beta}.
\]</span></p>
<p>No ponto de mínimo, <span class="math inline">\(\boldsymbol{\beta}=\hat{\boldsymbol{\beta}}\)</span> e o gradiente é igual a zero:</p>
<p><span class="math display">\[
-2\mathbf{X}^\top\mathbf{Y}
+
2\mathbf{X}^\top\mathbf{X}\hat{\boldsymbol{\beta}}
=
0,
\]</span></p>
<p><span class="math display">\[
\mathbf{X}^\top\mathbf{X}\hat{\boldsymbol{\beta}}
=
\mathbf{X}^\top\mathbf{Y}.
\]</span></p>
<p>Essas são as <strong>equações normais</strong> em forma matricial.</p>
<p>Se <span class="math inline">\(\mathbf{X}\)</span> possui posto completo de colunas, então <span class="math inline">\(\mathbf{X}^\top\mathbf{X}\)</span> é invertível e</p>
<p><span class="math display">\[
\boxed{
\hat{\boldsymbol{\beta}}
=
(\mathbf{X}^\top\mathbf{X})^{-1}
\mathbf{X}^\top\mathbf{Y}
}.
\]</span></p>
<p>Além disso, a matriz Hessiana da função <span class="math inline">\(S\)</span> é</p>
<p><span class="math display">\[
\mathbf{H}
=
2\mathbf{X}^\top\mathbf{X}.
\]</span></p>
<p>Quando <span class="math inline">\(\mathbf{X}\)</span> possui posto completo, <span class="math inline">\(\mathbf{X}^\top\mathbf{X}\)</span> é definida positiva. Portanto, o ponto crítico encontrado acima é o único mínimo global da soma de quadrados.</p>
<p>Também podemos utilizar a expressão matricial para encontrar os parâmetros.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(y <span class="sc">~</span> x)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>betas <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X) <span class="sc">%*%</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> y</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>betas</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      [,1]
(Intercept) -0.00842933501
x            0.00003059096</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>A expressão acima é útil para compreender a álgebra do MQO. Na prática computacional, não é recomendável formar explicitamente <span class="math inline">\((X^\top X)^{-1}\)</span> quando existem métodos numericamente mais estáveis. A função <code>lm()</code>, por exemplo, utiliza uma decomposição QR.</p>
</blockquote>
<p>E, para verificarmos que os cálculos coincidem:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept)              x 
-0.00842933501  0.00003059096 </code></pre>
</div>
</div>
<p>As três formas produzem os mesmos coeficientes, salvo diferenças numéricas de arredondamento.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-condensed table-striped table-hover caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MQO</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MQO_Mat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">R</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">B0</td>
<td style="text-align: right;">-0.0084293</td>
<td style="text-align: right;">-0.0084293</td>
<td style="text-align: right;">-0.0084293</td>
</tr>
<tr class="even">
<td style="text-align: left;">B1</td>
<td style="text-align: right;">0.0000306</td>
<td style="text-align: right;">0.0000306</td>
<td style="text-align: right;">0.0000306</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Esse é o método dos mínimos quadrados.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Gabriel Orso · Universidade Federal de Santa Maria</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Site construído com Quarto</p>
</div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>